[package]
name = "horizon-plugin-api"
version = "0.1.11"
edition = "2021"
authors = ["Tristan Poland <redstonecrafter126@gmail.com>"]
license = "MIT"
description = "Horizon Plugin Base Implementation"

[dependencies]
socketioxide = "0.15.1"
