[package]
name = "Horizon-Plugin-API"
version = "0.1.0"
edition = "2021"
authors = ["Tristan Poland <redstonecrafter126@gmail.com>"]
license = "MIT"
description = "Horizon Plugin Base Implementation"

[dependencies]
